name: mardod
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  # For Responsive App
  flutter_screenutil:
  # Amazing Animations For App
  animate_do:
  # State Management For(linked Database With App)
  get:
  # Amazing Fonts For Free used
  google_fonts:
  # Loading Shapes Amazing
  flutter_spinkit:

  # Date Format Package
  intl:

  # Terms And Conditions From Html To Flutter Widget
  flutter_widget_from_html: 0.15.2

  # Otp Code Shape
  pinput:

  # launch Email
  url_launcher:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
